language: php

php:
  - '7.1'

before_install:
  - openssl aes-256-cbc -K $encrypted_78ee7694ad99_key -iv $encrypted_78ee7694ad99_iv -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'noreply@travis-ci.com'
  - git clone https://github.com/sxyazi/blog-deploy.git

script:
  - cd blog-deploy
  - bash deploy.sh 'git@github.com:sxyazi/sxyazi.github.io.git' 'https://github.com/sxyazi/blog.git'
  - bash deploy.sh push 'git@github.com:sxyazi/sxyazi.github.io.git'

branches:
  only:
    - master
